name: Build Chromium for iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. リポジトリチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. depot_tools のインストールと PATH 設定
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ${HOME}/depot_tools
          echo "export PATH=\$PATH:${HOME}/depot_tools" >> $GITHUB_ENV
          echo "export PATH=${HOME}/depot_tools:\$PATH" >> ~/.zshrc
          echo "export PATH=${HOME}/depot_tools:\$PATH" >> ~/.bashrc

      # 3. PATH の確認
      - name: Verify depot_tools in PATH
        run: echo $PATH

      # 4. Chromium ソースコードのキャッシュを復元
      - name: Restore Chromium source cache
        uses: actions/cache@v3
        with:
          path: ./src
          key: ${{ runner.os }}-chromium-src
          restore-keys: |
            ${{ runner.os }}-chromium-src

      # 5. Chromium ソースコードを取得（キャッシュがない場合のみ）
      - name: Fetch Chromium source code
        run: |
          if [ ! -d "./src" ]; then
            fetch ios
            cd src
            gclient sync
          fi

      # 6. Chromium ソースコードをキャッシュ
      - name: Save Chromium source cache
        uses: actions/cache@v3
        with:
          path: ./src
          key: ${{ runner.os }}-chromium-src

      # 7. ビルド設定生成
      - name: Generate build configuration
        run: |
          cd src
          gn gen out/Default --args='target_os="ios" target_cpu="arm64"'

      # 8. Chromium のビルド
      - name: Build Chromium
        run: |
          cd src
          ninja -C out/Default chrome

      # 9. IPA の作成
      - name: Package IPA
        run: |
          cd src
          mkdir -p Payload
          cp -R out/Default/Chromium.app Payload/
          zip -r Chromium.ipa Payload

      # 10. リリースにアップロード
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./src/Chromium.ipa
          asset_name: Chromium.ipa
          asset_content_type: application/octet-stream
