name: Build Chromium for iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. リポジトリチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. depot_tools のインストール
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo 'export PATH=$PATH:${GITHUB_WORKSPACE}/depot_tools' >> $GITHUB_ENV

      # 3. Chromium ソースコードの取得
      - name: Fetch Chromium source code
        run: |
          fetch ios
          gclient sync

      # 4. ビルド設定生成
      - name: Generate build configuration
        run: |
          gn gen out/Default --args='target_os="ios" target_cpu="arm64"'

      # 5. Chromium のビルド
      - name: Build Chromium
        run: |
          ninja -C out/Default chrome

      # 6. IPA の作成
      - name: Package IPA
        run: |
          mkdir Payload
          cp -R out/Default/Chromium.app Payload/
          zip -r Chromium.ipa Payload

      # 7. リリースにアップロード
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Chromium.ipa
          asset_name: Chromium.ipa
          asset_content_type: application/octet-stream
